### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by flyke** [drupal-composer/drupal-paranoia#6]
I have tested this on linux (Debian 9 - via a vagrant box) with composer 1.6.5 and a simple composer.json file based very hard on drupal-composer/drupal-project with the modifications as described in the configuration section of drupal-paranoia.

When running composer install I get this error:

```
- Installing drupal/core (8.5.4):
                                                                                                  
  [RuntimeException]                                                                              
  Could not delete app/core/.git/objects/pack/pack-8445df06ad688ca62d2204f2d5de6550340fb381.idx:  

```
And the installer has stopped after that. I dont know if it completed everything, but I do have a generated app and htdocs folder. The app folder contains the 'core' folder but no drupal scaffold files.
The htdocs folder looks like this:
```
htdocs
  core
    modules
      statistics
        statistics.php
      install.php
      rebuild.php
  sites
    default
  index.php
```
If I manually run
```
composer drupal:paranoia
```
I get the error:
```
[InvalidArgumentException]                                                      
$from (/vagrant/htdocs/sites/default/files) and $to () must be absolute paths.
```

As a test, I try to manually force the generation of the drupal scaffold files:
```
composer drupal-scaffold
```
but then I get:
```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "drupal-scaffold" is not defined.                       
                                                                  
  Did you mean this?                                              
      drupal:scaffold
```

So instead I try:
```
composer drupal:scaffold
```
but then I get:
```
$ composer drupal:scaffold
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Composer\Installer\InstallationManager::getInstallPath() must implement interface Composer\Package\PackageInterface, null given, called in /v
agrant/vendor/drupal-composer/drupal-scaffold/src/Handler.php on line 270 and defined in phar:///usr/bin/composer.phar/src/Composer/Installer/InstallationManager.php:248
Stack trace:
#0 /vagrant/vendor/drupal-composer/drupal-scaffold/src/Handler.php(270): Composer\Installer\InstallationManager->getInstallPath(NULL)
#1 /vagrant/vendor/drupal-composer/drupal-scaffold/src/Handler.php(147): DrupalComposer\DrupalScaffold\Handler->getWebRoot()
#2 /vagrant/vendor/drupal-composer/drupal-scaffold/src/DrupalScaffoldCommand.php(31): DrupalComposer\DrupalScaffold\Handler->downloadScaffold()
#3 phar:///usr/bin/composer.phar/vendor/symfony/console/Command/Command.php(242): DrupalComposer\DrupalScaffold\DrupalScaffoldCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object
(Symfony\Component\Console\Output\ConsoleOutput))
#4 pha in phar:///usr/bin/composer.phar/src/Composer/Installer/InstallationManager.php on line 248

Fatal error: Uncaught TypeError: Argument 1 passed to Composer\Installer\InstallationManager::getInstallPath() must implement interface Composer\Package\PackageInterface, null given, called in /vagran
t/vendor/drupal-composer/drupal-scaffold/src/Handler.php on line 270 and defined in phar:///usr/bin/composer.phar/src/Composer/Installer/InstallationManager.php:248
Stack trace:
#0 /vagrant/vendor/drupal-composer/drupal-scaffold/src/Handler.php(270): Composer\Installer\InstallationManager->getInstallPath(NULL)
#1 /vagrant/vendor/drupal-composer/drupal-scaffold/src/Handler.php(147): DrupalComposer\DrupalScaffold\Handler->getWebRoot()
#2 /vagrant/vendor/drupal-composer/drupal-scaffold/src/DrupalScaffoldCommand.php(31): DrupalComposer\DrupalScaffold\Handler->downloadScaffold()
#3 phar:///usr/bin/composer.phar/vendor/symfony/console/Command/Command.php(242): DrupalComposer\DrupalScaffold\DrupalScaffoldCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object
(Symfony\Component\Console\Output\ConsoleOutput))
#4 pha in phar:///usr/bin/composer.phar/src/Composer/Installer/InstallationManager.php on line 248

```

This is my complete composer.json file:

```
{
    "name": "intracto/paranoiatest",
    "description": "Add a new blanco site",
    "type": "project",
    "authors": [
        {
            "name": "Joery Lemmens"
        }
    ],
    "require": {
        "composer/installers": "^1.0.21",
        "cweagans/composer-patches": "^1.6",
        "drupal-composer/drupal-paranoia": "~1",
        "drupal-composer/drupal-scaffold": "^2.5",
        "drupal/core": "^8.5",
        "drush/drush": "^9.2",
        "oomphinc/composer-installers-extender": "^1.1",
        "vlucas/phpdotenv": "^2.4",
        "webflo/drupal-finder": "^1.1",
        "webmozart/path-util": "^2.3"
    },
    "require-dev": {
        "webflo/drupal-core-require-dev": "~8.5.3"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true,
        "discard-changes": true
    },
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ],
        "files": ["load.environment.php"]
    },
    "scripts": {
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "installer-paths": {
            "app/core": ["type:drupal-core"],
            "app/profiles/{$name}": ["type:drupal-profile"],
            "app/modules/contrib/{$name}": ["type:drupal-module"],
            "app/modules/custom/{$name}": ["type:drupal-custom-module"],
            "app/themes/contrib/{$name}": ["type:drupal-theme"],
            "app/themes/custom/{$name}": ["type:drupal-custom-theme"],
            "app/libraries/{$name}": ["type:drupal-library"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        },
        "drupal-scaffold": {
            "initial": {
                ".editorconfig": "../.editorconfig",
                ".gitattributes": "../.gitattributes"
            }
        },
        "patches-file": "composer.patches.json",
        "drupal-app-dir": "app",
        "drupal-web-dir": "htdocs"
    },

    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}

```

**Comment by flyke** [comment]
Update: It works, this may be closed!

It was my fault. It works, even in Vagrant.
When it did not work, I started from an existing composer file we always use at our company and reformed it to match that of drupal-composer/drupal-project. But now I did a new test starting from a clean clone of drupal-composer/drupal-project and everything works fine.
